'use strict';

// tests for getProducts
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getProducts', '/handler.js', 'getProducts');

describe('getProducts', () => {
  before((done) => {
    done();
  });
  
  it('Should return 200 when fetching products', async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
    expect(response.body).to.not.be.empty;
    expect(response.statusCode).to.be.eql(200);
  });
});
